defaults:
  - modalities: default
  - optimizer: adam
  - _self_  # Add this line to include the current config file

data:
  source_file: "/mnt/data/erbauer/retargeting/retargeted_data_v4_faiveonly.npy"
  train_split: 0.8  # 80% for training, 20% for testing

model:
  embedding_dim: 256
  modalities: ${modalities}
  contrastive_loss_weight: 1.0  # Scaling parameter for contrastive loss

training:
  batch_size: 1024
  num_epochs: 100
  log_interval: 10
  debug: True
  save_interval: 1  # Save model every 10 epochs
  save_path: "/home/erbauer/robot_clip/checkpoints"  # Path to save the model checkpoints

wandb:
  project: "robot-clip"
  entity: "erikbauer"

optimizer:
  name: "Adam"
  lr: 0.001
  weight_decay: 0.0001

hydra:
  run:
    dir: .  # Set the working directory to the current directory
