defaults:
  - modalities: default
  - optimizer: adam
  - _self_

data:
  source_file: "/mnt/data/erbauer/retargeting/retargeted_data_v4_faiveonly.npy"
  train_split: 0.8  # 80% for training, 20% for testing

model:
  embedding_dim: 96
  modalities: ${modalities}
  contrastive_loss_weight: 1.0  # Scaling parameter for contrastive loss

training:
  batch_size: 1024
  encoder_epochs: 50  # Number of epochs for encoder training
  decoder_epochs: 50  # Number of epochs for decoder training
  log_interval: 10
  debug: false
  save_interval: 1
  save_path: "/home/erbauer/robot_clip/checkpoints"
  gpu_id: 0

wandb:
  project: "robot-clip-two-step"
  entity: "erikbauer"

optimizer:
  encoder:
    name: "Adam"
    lr: 0.001
    weight_decay: 0.0001
  decoder:
    name: "Adam"
    lr: 0.001
    weight_decay: 0.0001
